#服务端口配置
server:
  port: 8082
  servlet:
    context-path: /hangele


#springboot多数据源配置
#数据源1
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      blog:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        initialize: true
        name: blog
          #基本属性
          #测试
        jdbc-url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&autoReconnect=true
        username: root
        password: a123456
        min-idle: 5
        max-idle: 10
        max-wait: 10000
        initial-size: 5
        max-active: 20
        validation-query: SELECT 1
        test-on-borrow: false
        test-while-idle: true
        test-on-return: false
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
    mvc:
      static-path-pattern: /**
#http://localhost:8082/hangele/index.html 访问地址
#mybatis配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath*:com/blog/mapper/**/*.xml
  type-aliases-package: com.blog.mapper
#Mybatis分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#日志配置
logging:
  level:
    com.blog.mapper: debug
